### ISSUE TITLE
Restricted scoreboard show after toggling

### ISSUE THREAD

**Issue by nhanledev** [r4g3baby/SimpleScore#23]
Description:
- I set up a multi-scoreboard which restrict each base on permission (managed by luckperms). When toggle it off and then on again, the permission get ignored and it shows the first board in the config.
- The problem persist even after the server restart with `SaveScoreboards: true` in the config.

What to expect:
- Show only board which user has permission on after toggling like it was before toggling the board.

My config:
```
# Default time in ticks for a score to stay on the scoreboard (20 ticks = 1 second)
UpdateTime: 100

# Save which players have the scoreboard disabled
SaveScoreboards: true

# Whether to apply placeholders asynchronously or not
AsyncPlaceholders: true

# Enable this if you are running a 1.13+ server with backwards version support
ForceLegacy: false

# Configure your scoreboards layout
Scoreboards:
  normal_board:
    // board detail
viplv1_board:
    Restricted: true
    // board detail
viplv2_board:
    Restricted: true
    // board detail


# Set what scoreboards each world will be using
Worlds:
  world_lobby: ['viplv2_board', 'viplv1_board', 'normal_board']
  multiple: ['viplv2_board', 'viplv1_board', 'normal_board']
```
