### ISSUE TITLE
Feature Request: Add possibility for EQUALS_NOT condition or ELSE statements

### ISSUE THREAD

**Issue by NoelBank** [r4g3baby/SimpleScore#33]
I think it would be usefull to add this masterpiece of condition `EQUALS_NOT`.

This could then make the following possible:

```
if hasPermissionExample 
...

if hasNoPermissionExample 
...

```
it would be easier if you could simply pass an else statement:

```
    2:
      conditions: ["equalsOperationExample"]
      frames:
        - "&7You can see this line because you passed.."
        - "&7the &8equalsOperationExample &7condition."
      else: 
        frames:
          - "&7You can't see this line because you"
          - "&7didn't pass the &8equalsOperationExample &7condition."
```

Best regards!
