### ISSUE TITLE
Config.yml default regex suggestion

### ISSUE THREAD

**Issue by mattcapazz** [r4g3baby/SimpleScore#69]
### Plugin Version

not relevant 

### Server Version

nr

### Describe the Bug

```yaml
worlds:
  # If player doesn't meet the conditions to see the conditional scoreboard then it will display the simple scoreboard
  world_the_end: [ 'conditional', 'simple' ]
  # This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
  # "world_the_end" will never reach this line since it already matched above
  world_\w*: [ 'customTiming' ]
  # This will match all worlds that haven't been defined above
  '[\w ]*': [ 'simple' ]
  # Adding anything here will not work as it was already matched by the regex specified above
```
the default `config.yml` file concludes with this regex: `'[\w ]*'`

which pose issues for people that are not _regex-savy_ and with a world named `world-4...` because the regex only matches `a-zA-Z0-9_`(`\w`)

my recommendation is that the regex could be `.*` instead
